### ISSUE TITLE
[public] Players avoid "ghost" connecting clients

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1006]
Players who are connected but have yet to click "Join game" will show up as predicted_viewmodels. These viewmodels obstruct player movement since other clients will try to avoid them as if they were alive players.

1. Client A: create a game (nmo_suzhou is a good example for this)
2. Client B: connect to the game, but don't click "Join game"
3. Client B: press escape to preview your location, or just getpos

![20180607083237_1](https://user-images.githubusercontent.com/11559683/41097801-a0079df0-6a2f-11e8-901e-139572088a67.jpg)

4. Client A: go to those coordinates with `picker` enabled
5. Client A: try walking through this, you should get pushed around:

![20180607083306_1](https://user-images.githubusercontent.com/11559683/41097669-2c16f882-6a2f-11e8-8e03-b6e8fb2426b7.jpg)

I think these also the reason why you sometimes see a pair of arms floating around while in spectator mode, but I have no confirmation for that yet.

**Comment by DDysphie** [comment]
Seems fixed as of src-r4495/dev-r8829

**Comment by Mateos81** [comment]
Just a question: have you tested the case when a player already playing is standing on that position and the player has connected and is spawning at that moment? To be sure they don't get each other stuck (or die?)

**Comment by DDysphie** [comment]
Reopening because this still happens (but seemingly only during practice mode, which is better).
I can also only reproduce it on certain maps. No viewmodel spawns but players still avoid the coords where the camera is located at.

Only tested with SourceTV, no real players, I can't walk through this:

![20180703095912_1](https://user-images.githubusercontent.com/11559683/42221458-700fe750-7ea8-11e8-8b8c-bc9608f81c71.jpg)

**Comment by Bubka3** [comment]
> I can also only reproduce it on certain maps.
Can you reproduce it on an official map?

**Comment by Holycrapjimhox** [comment]
I can confirm that this still occurs on the public release of 1.1.0.0

**Comment by Dysphie** [comment]
This happens whenever the game calls for RespawnPlayers and someone is still connecting (hasn't yet clicked "Join Game"). Clients will attempt to avoid them already. nmo_miner_detour_v3 is simply the easiest to test because it calls this function a lot in this particular segment. Should also affect official maps with the right timing

**Comment by felis-catus** [comment]
Fixed by new player avoidance method introduced in 1.12.3.
