### ISSUE TITLE
(code) Zombies seemingly attracted towards env_fire?

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#612]
This is a minor observation, but some maps (Brooklyn is the big one, Chinatown was the other one I noticed), if there's an area with a fire entity and a zombie spawn brush near it, the zombies that spawn in tend to gather around the fire in a big group; you can easily see this happening on Brooklyn outside the Car Repair Shop, or in Chinatown by the little Repair Shop on the street (with the fire and the military barricade)

If it happens it generally screws up the difficulty in the area it occurs in, since survivors can just breeze past the NPCs

---

Steps to Reproduce
1) Load up nmo_brooklyn
2) Progress through the map till you get to the car repair shop
3) Wait a few seconds for the zombies to populate the area past the gate, before exiting the shop and onto the street

If done correctly you'll see around 20 to 30 zombies idly standing right on top of the env_fire entity on the street level, slowly burning themselves to death

**Comment by Winning117** [comment]
Confirmed fixed in src-r4405/dev-r8773, needs to be closed.

**Comment by DDysphie** [comment]
I don't see any indication that this was touched. What other issues tackles this?

**Comment by Winning117** [comment]
No idea what issues tackled this but this is 4 years old and I just tested it on chinatown and brooklyn and the zombies don't pile up like they do in repro steps.

**Comment by AtheistNMRiH** [comment]
is still happens sometimes, I was playing on brooklyn in dev build

**Comment by Winning117** [comment]
Interesting. We'll have to investigate further to see if anything makes it consistently reproducible.

**Comment by felis-catus** [comment]
Couldn't find any logic in code that would attract zombies to env_fire, closing.
