### ISSUE TITLE
(dev) nmo_junction (map bugs)

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#908]
The map version is the one found in r-4348

**• Objective item softlocks:**
1) Propane softlocks:
![nmo_junction0003](https://user-images.githubusercontent.com/35630284/37878941-b3b255de-3046-11e8-87d6-0d12e54ef400.jpg)
![nmo_junction0004](https://user-images.githubusercontent.com/35630284/37878942-b3d780ac-3046-11e8-8273-70de695ac360.jpg)
![nmo_junction0006](https://user-images.githubusercontent.com/35630284/37878943-b3f80cbe-3046-11e8-820b-036b18c41538.jpg)
![nmo_junction0007](https://user-images.githubusercontent.com/35630284/37878944-b41a991e-3046-11e8-80a2-b20595aa5528.jpg)
![nmo_junction0009](https://user-images.githubusercontent.com/35630284/37878945-b43b73b4-3046-11e8-883b-b6db72a79c68.jpg)
![nmo_junction0011](https://user-images.githubusercontent.com/35630284/37878946-b45c95a8-3046-11e8-820a-6ec4186fae26.jpg)
![nmo_junction0012](https://user-images.githubusercontent.com/35630284/37878947-b47e3028-3046-11e8-890f-d35e57801ad4.jpg)
![nmo_junction0013](https://user-images.githubusercontent.com/35630284/37878948-b4a407b2-3046-11e8-8708-9332c5ab6c86.jpg)
![nmo_junction0014](https://user-images.githubusercontent.com/35630284/37878949-b4c599b8-3046-11e8-8970-c3328c4a4a5a.jpg)
![nmo_junction0015](https://user-images.githubusercontent.com/35630284/37878950-b4e717d2-3046-11e8-9185-30b7419e8575.jpg)
![nmo_junction0016](https://user-images.githubusercontent.com/35630284/37878951-b510a46c-3046-11e8-99ce-90c256d3c46d.jpg)
![nmo_junction0017](https://user-images.githubusercontent.com/35630284/37878952-b5329536-3046-11e8-9792-f43e359f0ce0.jpg)
![nmo_junction0018](https://user-images.githubusercontent.com/35630284/37878953-b558c508-3046-11e8-9007-964d78ea4c83.jpg)
(this last one is tricky to do on a real match, but it's more than possible)

2) Welder softlocks:
NOTE: a really dedicated troll is most likely to do these, since you have to remain alive to hold the second welder in your inventory. Still, relatively easy to do all of them, so fixing them is important.
![nmo_junction0019](https://user-images.githubusercontent.com/35630284/37878973-27e32bc2-3047-11e8-8878-8b29f88c0f7b.jpg)
![nmo_junction0020](https://user-images.githubusercontent.com/35630284/37878974-28042246-3047-11e8-8972-afe686854f70.jpg)
![nmo_junction0021](https://user-images.githubusercontent.com/35630284/37878975-28243504-3047-11e8-9b98-e737a0895a8b.jpg)
(you can grab back the welder from under the shelves, but a new player may struggle to find out how)
![nmo_junction0022](https://user-images.githubusercontent.com/35630284/37878976-284dc4fa-3047-11e8-95ed-ecf66e61a8a5.jpg)
![nmo_junction0023](https://user-images.githubusercontent.com/35630284/37878977-286de5fa-3047-11e8-801f-44da99311a73.jpg)

3) Tunnel key softlocks:
![nmo_junction0028](https://user-images.githubusercontent.com/35630284/37878994-62cd20ee-3047-11e8-8271-5431d45ec375.jpg)
![nmo_junction0029](https://user-images.githubusercontent.com/35630284/37878995-62f1a5b8-3047-11e8-8140-1885033279a4.jpg)
(same thing with the welder, the key can be retrieved, but a new player may struggle to find the way)

4) TNT softlocks:
![nmo_junction0031](https://user-images.githubusercontent.com/35630284/37879007-a6b6b1c6-3047-11e8-8cfd-2a606f0a09cc.jpg)
![nmo_junction0034](https://user-images.githubusercontent.com/35630284/37879008-a6d81c62-3047-11e8-86ca-7edcd6e10db6.jpg)
![nmo_junction0035](https://user-images.githubusercontent.com/35630284/37879009-a6fac4ba-3047-11e8-853a-2e7b84e7ce6f.jpg)
(same with the key and welder, a new player can have trouble retrieving it from there)
![nmo_junction0036](https://user-images.githubusercontent.com/35630284/37879010-a71b2f52-3047-11e8-98a5-e02bb9f087ea.jpg)
![nmo_junction0037](https://user-images.githubusercontent.com/35630284/37879011-a73d26de-3047-11e8-844e-22d7f1924403.jpg)

**• Other softlocks:**
This is something trolls can use to cause a softlock for other players. Basically, stand on the back of the escape truck, aim at the driver seats, and gradually press E several times while holding W. The truck will start moving away from the ladders way sooner than intended, before the explosions start. This causes a softlock for other players, since there is an instant death trigger on the floor of the tunnel.
![nmo_junction0038](https://user-images.githubusercontent.com/35630284/37879080-f1fc08ba-3048-11e8-944b-e185b172a268.jpg)
![nmo_junction0039](https://user-images.githubusercontent.com/35630284/37879081-f21df484-3048-11e8-9917-01e8fe283bc0.jpg)
(that was the first explosion)

**• Map oddities:**
1) The door to the pawnshop allows you to interact with the keypad after typing the correct code. It can lead to players getting stuck in place and getting killed:
![nmo_junction0024](https://user-images.githubusercontent.com/35630284/37879176-aff54dbc-304a-11e8-9e13-ae4642bd772c.jpg)

2) You can see through the door to the tunnel:
![nmo_junction0030](https://user-images.githubusercontent.com/35630284/37879189-c2c11700-304a-11e8-8459-3cea1e12ec0f.jpg)

3) The same door closes on its own:
![nmo_junction0032](https://user-images.githubusercontent.com/35630284/37879192-cd9f73ec-304a-11e8-8104-1fa98455c21c.jpg)
![nmo_junction0033](https://user-images.githubusercontent.com/35630284/37879193-cdc380de-304a-11e8-815b-164a8a6db1c2.jpg)

**Comment by AtheistNMRiH** [comment]
I think self closing door is intentional

**Comment by Holycrapjimhox** [comment]
On "map oddities" I just report things that look weird to me. If the door closing is intentional, then leave it as is.

**Comment by Holycrapjimhox** [comment]
EDIT: By Atheist's request, I merged my post with his.

**Comment by Holycrapjimhox** [comment]
More softlocks found by Winning117: https://github.com/nmrih/source-game/issues/914

**Comment by Holycrapjimhox** [comment]
EDIT: Added one more key softlock and a couple other Map oddities.

**Comment by Winning117** [comment]
Not fixed in dev-r8775 which was supposed to fix this. All of these areas have been covered with playerclip brushes instead of itemclip brushes on accident :p

**Comment by Winning117** [comment]
Many of these issues are still present in src-r4405/dev-r8787 which "Fixed multiple locations objective items could be put out of reach of players."

**Comment by AtheistNMRiH** [comment]
check again in r8791, everything should be fixed

**Comment by Winning117** [comment]
The following are still not fixed in src-r4405/dev-r8791

![224260_20180425231909_1](https://user-images.githubusercontent.com/15934200/39290414-51b0b4fa-48e4-11e8-80bd-387f9431697d.png)
![224260_20180425231943_1](https://user-images.githubusercontent.com/15934200/39290415-51cdccca-48e4-11e8-8863-2aba94023129.png)
![224260_20180425232022_1](https://user-images.githubusercontent.com/15934200/39290416-51e952d8-48e4-11e8-8870-5b4ad411140b.png)
![224260_20180425233320_1](https://user-images.githubusercontent.com/15934200/39290417-52044c32-48e4-11e8-83d5-51dedc29eb61.png)
![224260_20180425233744_1](https://user-images.githubusercontent.com/15934200/39290418-52211574-48e4-11e8-9b71-9d6b8c742b42.png)
![224260_20180425233759_1](https://user-images.githubusercontent.com/15934200/39290419-5241e3ee-48e4-11e8-968b-c0284d2702b1.png)
![224260_20180425233833_1](https://user-images.githubusercontent.com/15934200/39290420-527961ca-48e4-11e8-94d3-927813d76101.png)
